In [32]:
##CS595 ASSIGNMENT-3
##Decision Tree
import pandas as pd
import numpy as np
import csv
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn import tree
from sklearn import metrics
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.model_selection import  cross_val_score
from sklearn.preprocessing import Imputer

In [ ]:
##For the FBI to develop predictive models for crime, to help the Bureau and police departments around the country to use machine learning 
##to better focus their resources on locations where crimes are more likely to be committed.
##We are expected to implement solution. 

In [33]:
data=pd.read_csv("C:\\Users\\Dell\\Desktop\\CS595_IML\\communities.csv")

In [34]:
data

state        communityname  fold  population  householdsize  \
0         1        Alabastercity     7        0.01           0.61   
1         1    AlexanderCitycity    10        0.01           0.41   
2         1         Annistoncity     3        0.03           0.34   
3         1           Athenscity     8        0.01           0.38   
4         1           Auburncity     1        0.04           0.37   
5         1         Bessemercity     6        0.04           0.44   
6         1       Birminghamcity     2        0.41           0.37   
7         1          Cullmancity     1        0.01           0.30   
8         1           Daphnecity     7        0.00           0.39   
9         1          Decaturcity    10        0.06           0.39   
10        1           Dothancity     4        0.07           0.41   
11        1       Enterprisecity     2        0.02           0.43   
12        1          Eufaulacity     5        0.01           0.46   
13        1        Fairfieldcity     1        0.00           0.45   
14        1         Florencecity     3        0.04           0.33   
15        1        FortPaynecity     2        0.00           0.35   
16        1          Gadsdencity     9        0.05           0.32   
17        1        Hartsellecity     4        0.00           0.43   
18        1         Homewoodcity     5        0.02           0.23   
19        1           Hoovercity    10        0.05           0.35   
20        1         Hueytowncity     4        0.01           0.44   
21        1       Huntsvillecity     1        0.24           0.37   
22        1     Jacksonvillecity     7        0.00           0.54   
23        1           Jaspercity     8        0.01           0.37   
24        1          Madisoncity     5        0.01           0.36   
25        1           Mobilecity     8        0.30           0.41   
26        1       Montgomerycity     2        0.28           0.45   
27        1    MountainBrookcity     8        0.02           0.37   
28        1        Northportcity     2        0.01           0.44   
29        1          Opelikacity     6        0.02           0.45   
...     ...                  ...   ...         ...            ...   
1963     55        NewBerlincity     4        0.04           0.55   
1964     55         OakCreekcity     6        0.02           0.49   
1965     55       Oconomowoccity     6        0.00           0.42   
1966     55         Onalaskacity     4        0.00           0.44   
1967     55          Oshkoshcity     7        0.07           0.42   
1968     55           Racinecity    10        0.12           0.44   
1969     55       RiverFallscity     3        0.00           0.67   
1970     55        Sheboygancity     8        0.06           0.37   
1971     55     Shorewoodvillage     6        0.01           0.18   
1972     55   SouthMilwaukeecity     9        0.02           0.39   
1973     55     StevensPointcity     4        0.02           0.51   
1974     55       SunPrairiecity     2        0.01           0.48   
1975     55         Superiorcity     8        0.03           0.34   
1976     55        TwoRiverscity     6        0.00           0.37   
1977     55        Watertowncity     2        0.00           0.52   
1978     55         Waukeshacity     6        0.08           0.45   
1979     55           Wausaucity     7        0.04           0.37   
1980     55        Wauwatosacity     9        0.06           0.35   
1981     55        WestAlliscity     6        0.09           0.29   
1982     55         WestBendcity     3        0.02           0.49   
1983     55  WhitefishBayvillage     9        0.01           0.42   
1984     55       Whitewatercity     6        0.00           0.65   
1985     55  WisconsinRapidscity     8        0.01           0.32   
1986     56         Cheyennecity     4        0.06           0.34   
1987     56         Evanstoncity     6        0.00           0.65   
1988     56         Gillettecity     9        0.01           0.53   
1989

In [35]:
data.describe()

state         fold   population  householdsize  racepctblack  \
count  1993.000000  1993.000000  1993.000000    1993.000000   1993.000000   
mean     28.683894     5.496237     0.057612       0.463437      0.179227   
std      16.401661     2.872650     0.126935       0.163747      0.252870   
min       1.000000     1.000000     0.000000       0.000000      0.000000   
25%      12.000000     3.000000     0.010000       0.350000      0.020000   
50%      34.000000     5.000000     0.020000       0.440000      0.060000   
75%      42.000000     8.000000     0.050000       0.540000      0.230000   
max      56.000000    10.000000     1.000000       1.000000      1.000000   

       racePctWhite  racePctAsian  racePctHisp  agePct12t21  agePct12t29  \
count   1993.000000   1993.000000  1993.000000  1993.000000  1993.000000   
mean       0.753984      0.153753     0.144089     0.424210     0.493914   
std        0.243807      0.208905     0.232531     0.155234     0.143584   
min        0.000000      0.000000     0.000000     0.000000     0.000000   
25%        0.630000      0.040000     0.010000     0.340000     0.410000   
50%        0.850000      0.070000     0.040000     0.400000     0.480000   
75%        0.940000      0.170000     0.160000     0.470000     0.540000   
max        1.000000      1.000000     1.000000     1.000000     1.000000   

              ...           PctForeignBorn  PctBornSameState  PctSameHouse85  \
count         ...              1993.000000       1993.000000     1993.000000   
mean          ...                 0.215655          0.608776        0.534967   
std           ...                 0.231146          0.204314        0.181360   
min           ...                 0.000000          0.000000        0.000000   
25%           ...                 0.060000          0.470000        0.420000   
50%           ...                 0.130000          0.630000        0.540000   
75%           ...                 0.280000          0.770000        0.660000   
max           ...                 1.000000          1.000000        1.000000   

       PctSameCity85  PctSameState85     LandArea      PopDens  \
count    1993.000000     1993.000000  1993.000000  1993.000000   
mean        0.626322        0.651470     0.065243     0.232910   
std         0.200520        0.198253     0.109485     0.203127   
min         0.000000        0.000000     0.000000     0.000000   
25%         0.520000        0.560000     0.020000     0.100000   
50%         0.670000        0.700000     0.040000     0.170000   
75%         0.770000        0.790000     0.070000     0.280000   
max         1.000000        1.000000     1.000000     1.000000   

       PctUsePubTrans  LemasPctOfficDrugUn  ViolentCrimesPerPop  
count     1993.000000          1993.000000          1993.000000  
mean         0.161741             0.094099             0.237983  
std          0.229099             0.240379             0.233043  
min          0.000000             0.000000             0.000000  
25%          0.020000             0.000000             0.070000  
50%          0.070000             0.000000             0.150000  
75%          0.190000             0.000000             0.330000  
max          1.000000             1.000000             1.000000  

[8 rows x 103 columns]

In [36]:
data

state        communityname  fold  population  householdsize  \
0         1        Alabastercity     7        0.01           0.61   
1         1    AlexanderCitycity    10        0.01           0.41   
2         1         Annistoncity     3        0.03           0.34   
3         1           Athenscity     8        0.01           0.38   
4         1           Auburncity     1        0.04           0.37   
5         1         Bessemercity     6        0.04           0.44   
6         1       Birminghamcity     2        0.41           0.37   
7         1          Cullmancity     1        0.01           0.30   
8         1           Daphnecity     7        0.00           0.39   
9         1          Decaturcity    10        0.06           0.39   
10        1           Dothancity     4        0.07           0.41   
11        1       Enterprisecity     2        0.02           0.43   
12        1          Eufaulacity     5        0.01           0.46   
13        1        Fairfieldcity     1        0.00           0.45   
14        1         Florencecity     3        0.04           0.33   
15        1        FortPaynecity     2        0.00           0.35   
16        1          Gadsdencity     9        0.05           0.32   
17        1        Hartsellecity     4        0.00           0.43   
18        1         Homewoodcity     5        0.02           0.23   
19        1           Hoovercity    10        0.05           0.35   
20        1         Hueytowncity     4        0.01           0.44   
21        1       Huntsvillecity     1        0.24           0.37   
22        1     Jacksonvillecity     7        0.00           0.54   
23        1           Jaspercity     8        0.01           0.37   
24        1          Madisoncity     5        0.01           0.36   
25        1           Mobilecity     8        0.30           0.41   
26        1       Montgomerycity     2        0.28           0.45   
27        1    MountainBrookcity     8        0.02           0.37   
28        1        Northportcity     2        0.01           0.44   
29        1          Opelikacity     6        0.02           0.45   
...     ...                  ...   ...         ...            ...   
1963     55        NewBerlincity     4        0.04           0.55   
1964     55         OakCreekcity     6        0.02           0.49   
1965     55       Oconomowoccity     6        0.00           0.42   
1966     55         Onalaskacity     4        0.00           0.44   
1967     55          Oshkoshcity     7        0.07           0.42   
1968     55           Racinecity    10        0.12           0.44   
1969     55       RiverFallscity     3        0.00           0.67   
1970     55        Sheboygancity     8        0.06           0.37   
1971     55     Shorewoodvillage     6        0.01           0.18   
1972     55   SouthMilwaukeecity     9        0.02           0.39   
1973     55     StevensPointcity     4        0.02           0.51   
1974     55       SunPrairiecity     2        0.01           0.48   
1975     55         Superiorcity     8        0.03           0.34   
1976     55        TwoRiverscity     6        0.00           0.37   
1977     55        Watertowncity     2        0.00           0.52   
1978     55         Waukeshacity     6        0.08           0.45   
1979     55           Wausaucity     7        0.04           0.37   
1980     55        Wauwatosacity     9        0.06           0.35   
1981     55        WestAlliscity     6        0.09           0.29   
1982     55         WestBendcity     3        0.02           0.49   
1983     55  WhitefishBayvillage     9        0.01           0.42   
1984     55       Whitewatercity     6        0.00           0.65   
1985     55  WisconsinRapidscity     8        0.01           0.32   
1986     56         Cheyennecity     4        0.06           0.34   
1987     56         Evanstoncity     6        0.00           0.65   
1988     56         Gillettecity     9        0.01           0.53   
1989

In [37]:
data

state        communityname  fold  population  householdsize  \
0         1        Alabastercity     7        0.01           0.61   
1         1    AlexanderCitycity    10        0.01           0.41   
2         1         Annistoncity     3        0.03           0.34   
3         1           Athenscity     8        0.01           0.38   
4         1           Auburncity     1        0.04           0.37   
5         1         Bessemercity     6        0.04           0.44   
6         1       Birminghamcity     2        0.41           0.37   
7         1          Cullmancity     1        0.01           0.30   
8         1           Daphnecity     7        0.00           0.39   
9         1          Decaturcity    10        0.06           0.39   
10        1           Dothancity     4        0.07           0.41   
11        1       Enterprisecity     2        0.02           0.43   
12        1          Eufaulacity     5        0.01           0.46   
13        1        Fairfieldcity     1        0.00           0.45   
14        1         Florencecity     3        0.04           0.33   
15        1        FortPaynecity     2        0.00           0.35   
16        1          Gadsdencity     9        0.05           0.32   
17        1        Hartsellecity     4        0.00           0.43   
18        1         Homewoodcity     5        0.02           0.23   
19        1           Hoovercity    10        0.05           0.35   
20        1         Hueytowncity     4        0.01           0.44   
21        1       Huntsvillecity     1        0.24           0.37   
22        1     Jacksonvillecity     7        0.00           0.54   
23        1           Jaspercity     8        0.01           0.37   
24        1          Madisoncity     5        0.01           0.36   
25        1           Mobilecity     8        0.30           0.41   
26        1       Montgomerycity     2        0.28           0.45   
27        1    MountainBrookcity     8        0.02           0.37   
28        1        Northportcity     2        0.01           0.44   
29        1          Opelikacity     6        0.02           0.45   
...     ...                  ...   ...         ...            ...   
1963     55        NewBerlincity     4        0.04           0.55   
1964     55         OakCreekcity     6        0.02           0.49   
1965     55       Oconomowoccity     6        0.00           0.42   
1966     55         Onalaskacity     4        0.00           0.44   
1967     55          Oshkoshcity     7        0.07           0.42   
1968     55           Racinecity    10        0.12           0.44   
1969     55       RiverFallscity     3        0.00           0.67   
1970     55        Sheboygancity     8        0.06           0.37   
1971     55     Shorewoodvillage     6        0.01           0.18   
1972     55   SouthMilwaukeecity     9        0.02           0.39   
1973     55     StevensPointcity     4        0.02           0.51   
1974     55       SunPrairiecity     2        0.01           0.48   
1975     55         Superiorcity     8        0.03           0.34   
1976     55        TwoRiverscity     6        0.00           0.37   
1977     55        Watertowncity     2        0.00           0.52   
1978     55         Waukeshacity     6        0.08           0.45   
1979     55           Wausaucity     7        0.04           0.37   
1980     55        Wauwatosacity     9        0.06           0.35   
1981     55        WestAlliscity     6        0.09           0.29   
1982     55         WestBendcity     3        0.02           0.49   
1983     55  WhitefishBayvillage     9        0.01           0.42   
1984     55       Whitewatercity     6        0.00           0.65   
1985     55  WisconsinRapidscity     8        0.01           0.32   
1986     56         Cheyennecity     4        0.06           0.34   
1987     56         Evanstoncity     6        0.00           0.65   
1988     56         Gillettecity     9        0.01           0.53   
1989

In [38]:
def decisionTree():
    return tree.DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [39]:
def extractData(filename,communities,addstate = False,addcommunity = False):
    features = []
    xPositive=[]
    yPositive=[]
    xNegative=[]
    yNegative =[]
    with open(filename, 'r') as csvfile:
        filereader = csv.reader(csvfile)
        j = 0
        for i in filereader:
            if j > 0:
                data = i[3:len(i)-1]
                if addstate:
                    state = [0.0]*56
                    state[int(i[0])-1] = 1.0
                    data = data + state
                    features = features + ["state"+str(i) for i in range(56)]
                if addcommunity:
                    tmp = [0.0]*len(communities)
                    tmp[communities.index(i[1])] = 1.0
                    data = data + tmp
                    features = features + communities
                vect = np.array(data)
                #vect = np.array(i[3:len(i)-1])
                #x.append(vect.astype(np.float))
                if float(i[-1]) > 0.1:
                    xPositive.append(vect.astype(np.float))
                    yPositive.append(1)
                else:
                    xNegative.append(vect.astype(np.float))
                    yNegative.append(0)
            else:
                features = i[3:len(i)-1]
            j+=1
        """yPositive = np.array(yPositive)
        xPositive = np.array(xPositive)
        yNegative = np.array(yNegative)
        xNegative = np.array(xNegative)"""
        features = np.array(features)
        indxP = int(len(xPositive)*.6)
        indxN = int(len(xNegative)*.6)
        xTrain = xPositive[:indxP] + xNegative[:indxN]
        yTrain = yPositive[:indxP] + yNegative[:indxN]
        xTest = xPositive[indxP:] + xNegative[indxN:]
        yTest = yPositive[indxP:] + yNegative[indxN:]
        
        
            
            
        return xTrain,yTrain,xTest,yTest,features




In [40]:
#X, y = data.iloc[:,:-1], data.iloc[:, -1]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=1)


In [41]:
#from sklearn.cross_validation import train_test_split
#X, y = data.iloc[:,:-1], data.iloc[:, -1]
#X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.66, random_state=1)

In [42]:
def findCommunities():
    communities = []
    with open('C:\\Users\\Dell\\Desktop\\CS595_IML\\communities.csv', 'r') as csvfile:
        filereader = csv.reader(csvfile)
        j = 0
        for i in filereader:
            if j > 0:
                if i[1] not in communities:
                    communities.append(i[1])
            j+=1
    return communities

In [43]:
distintCommunities = findCommunities()
filename = 'C:\\Users\\Dell\\Desktop\\CS595_IML\\communities.csv'
x_Train,y_Train,x_Test,y_Test,features= extractData(filename,distintCommunities,addstate = False,addcommunity = False)

In [45]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = DecisionTreeClassifier(random_state=0)

In [46]:
data['highcrime'] = data['ViolentCrimesPerPop'].map(lambda x: True if x > 0.1 else False)

In [47]:
mylist=data['highcrime'].value_counts()
true_percent = (mylist[1]/(data['highcrime'].shape))*100
false_percent =(mylist[0]/(data['highcrime'].shape))*100
print("true percetage is %2f " %true_percent)
print("false percentage is %2f "%false_percent)

true percetage is 62.719518 
false percentage is 37.280482 


In [48]:
d1= data.copy()
del d1['state']
del d1['communityname']
del d1['fold']
del d1['highcrime']
del d1['ViolentCrimesPerPop']

In [49]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

Accuracy: 1.000000
(array([ 1.,  1.]), array([ 1.,  1.]), array([ 1.,  1.]), array([ 743, 1250], dtype=int64))


In [ ]:
##Decision tree depth analysis

In [71]:
dt_m1=decisionTree()
dt_m1.fit(x_Train,y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [ ]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

In [72]:
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=1,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=1,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [73]:
dt_m1=decisionTree()
dt_m1.fit(x_Train,y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [74]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

Accuracy: 1.000000
(array([ 1.,  1.]), array([ 1.,  1.]), array([ 1.,  1.]), array([ 743, 1250], dtype=int64))


In [53]:
dt_m2=decisionTree()
dt_m2.fit(x_Train,y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [54]:
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=2,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [55]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

Accuracy: 1.000000
(array([ 1.,  1.]), array([ 1.,  1.]), array([ 1.,  1.]), array([ 743, 1250], dtype=int64))


In [56]:
dt_m3=decisionTree()
dt_m3.fit(x_Train,y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [57]:
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [58]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

Accuracy: 1.000000
(array([ 1.,  1.]), array([ 1.,  1.]), array([ 1.,  1.]), array([ 743, 1250], dtype=int64))


In [59]:
dt_m4=decisionTree()
dt_m4.fit(x_Train,y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [60]:
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [61]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

Accuracy: 1.000000
(array([ 1.,  1.]), array([ 1.,  1.]), array([ 1.,  1.]), array([ 743, 1250], dtype=int64))


In [62]:
dt_m5=decisionTree()
dt_m5.fit(x_Train,y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [63]:
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [64]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

Accuracy: 1.000000
(array([ 1.,  1.]), array([ 1.,  1.]), array([ 1.,  1.]), array([ 743, 1250], dtype=int64))


In [65]:
dt_m6=decisionTree()
dt_m6.fit(x_Train,y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [66]:
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [67]:
clf = tree.DecisionTreeClassifier()
from sklearn.metrics import precision_recall_fscore_support
without_split_clf = clf.fit(d1,data['highcrime'])
prediction = without_split_clf.predict(d1)
print("Accuracy: %2f" %clf.score(d1,data['highcrime']))
print(precision_recall_fscore_support(data['highcrime'],prediction))

Accuracy: 1.000000
(array([ 1.,  1.]), array([ 1.,  1.]), array([ 1.,  1.]), array([ 743, 1250], dtype=int64))


In [80]:
import graphviz
dot_data = tree.export_graphviz(clf, out_file=data) 
graph = graphviz.Source(dot_data) 
graph.render("data") 

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
##Analysis
##The accuracy is 1.000 same  in all depths ,even if I apply several preprocessing methods.
##The tree doesn't make sense as the accuracy is 1.00.
##The performance of both train and test were not fine as there is no change in the depth of the tree.